services:
  - type: web
    name: tessera-backend
    env: docker
    rootDir: tessera-backend
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: tessera.cors.allowed-origins
        value: "https://personal-finance-manager-frontends.vercel.app"
    healthCheckPath: /api/health
